name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fix known_hosts mismatch
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -R github.com || true
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Checkout submodules
        run: git submodule update --init --recursive
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      - name: Run full test
        run: ./full-test.sh
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      - name: Cleanup
        if: always()
        run: ssh-add -D
